=== albertobolina/JAVA-xml/xsd_event_management/event.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    targetNamespace="http://www.eventmanagement.com/event"
    xmlns:ns="http://www.eventmanagement.com/event"
    elementFormDefault="qualified">
    
    <xs:include schemaLocation="pessoa.xsd"/>
    <xs:include schemaLocation="local.xsd"/>

    <xs:element name="event">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nome" type="xs:string"/>
                <xs:element name="descricao" type="xs:string"/>
                <xs:element name="precoBilhete" type="xs:decimal"/>
                <xs:element name="dataInicio" type="xs:dateTime"/>
                <xs:element name="dataFinal" type="xs:dateTime"/>
                <xs:element name="organizador" type="ns:pessoa"/>
                <xs:element name="local" type="ns:local"/>
                <xs:element name="participante" type="ns:pessoa" minOccurs="3" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== albertobolina/JAVA-xml/xsd_event_management/evento.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:event id="123456"
    xmlns:tns="http://www.eventmanagement.com/event"
    xmlns:tns2="http://www.eventmanagement.com/common"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.eventmanagement.com/event event.xsd">
    
    <tns:nome>MEO Sudoeste</tns:nome>
    <tns:descricao>Festival de verão</tns:descricao>
    <tns:precoBilhete>50.00</tns:precoBilhete>
    <tns:dataInicio>2024-08-02T09:00:00</tns:dataInicio>
    <tns:dataFinal>2024-08-09T09:00:00</tns:dataFinal>
    <tns:organizador id="234567">
        <tns:nome>Macaco do chinês</tns:nome>
        <tns:email>macacodochines@gmail.com</tns:email>
        <tns:telefone>9612345672</tns:telefone>
    </tns:organizador>

</tns:event>
